-- 0000_initial_schema.sql
-- This is the foundational migration for the project.
-- All subsequent schema changes will be added in new migration files. 

create table todos (
  id bigint generated by default as identity primary key,
  task text not null,
  is_completed boolean default false not null,
  created_at timestamptz default now() not null
); 